In [21]:
import numpy as np

In [22]:
a = np.array([1,2,3,4,5])
b=  np.array([5,4,3,7,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 7 1]


In [23]:
type(a)

numpy.ndarray

In [25]:
print(a+b)
print(a*b)

[ 6  6  6 11  6]
[ 5  8  9 28  5]


In [24]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [30]:
print(x.ndim)

2


In [27]:
print(x.dtype)

int64


In [36]:
np.arange(10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [38]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
np.random.randint(10,40, size=(3,5))

array([[37, 14, 11, 19, 20],
       [25, 35, 13, 15, 37],
       [22, 13, 18, 34, 20]], dtype=int32)

In [42]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])

y=np.array([[1,8,3],
          [3,7,2],
          [2,5,3]])
print(x)
print(y)


[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [ ]:
print(x*y) #normal multiplication

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [46]:
print(x@y)       #matrix multiplication
print(x.dot(y))  

[[19 85 34]
 [21 61 22]
 [20 64 22]]
[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [50]:
x.prod() #product of all element 

np.int64(12600)

In [ ]:
x.sum() 

np.int64(30)

In [53]:
x.mean()

np.float64(3.3333333333333335)

In [ ]:
x.mean(axis =0) #mean of each column

array([4., 4., 2.])

In [ ]:
x.mean(axis=1) #mean of each row 

array([4., 3., 3.])

In [56]:
print(x.var()) #variance of all element 
print(x.std()) #standard deviation of all element
print(x.min()) #minimum of all element 
print(x.max()) #maximum of all element 

3.3333333333333335
1.8257418583505538
1
7


In [63]:
z= np.array([1,2,3,4,5,6,7,8,9])  #median of all element
print(np.percentile(z,25)) #25th percentile
print(np.percentile(z,50)) #50th percentile
print(np.percentile(z,75)) #75th percentile

3.0
5.0
7.0


In [66]:
arr = np.array([[16,44,46,49],[10,22,41,35],[11,35,20,12],[46,33,41,36]])
print(arr)

[[16 44 46 49]
 [10 22 41 35]
 [11 35 20 12]
 [46 33 41 36]]


In [68]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 22]
 [41 35]
 [11 35]
 [20 12]
 [46 33]
 [41 36]]


In [70]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[16 44 46 49 10 22 41 35]
 [11 35 20 12 46 33 41 36]]
